project:
  type: website

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

freeze: true

# Metadata stuff
pagetitle: "Sara C. Kingsley"
author-meta: "Sara C. Kingsley"

website:
  title: "Sara Kingsley"
  description: "Sara C. Kingsley is a teaching faculty and researcher at Carnegie Mellon University, researching AI Security & Safety, and teaching applied Generative AI methods and engineering and data science."
  favicon: "/files/favicon-512.png"
  site-url: "https://github.com/sarakingsley/sara.kingsley"
  repo-url: "https://github.com/sarakingsley/sara.kingsley"

  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "CV"
        href: "cv/index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Research"
        file: research/index.qmd
      - text: "Teaching"
        href: "teaching/index.qmd"
      - text: "Talks"
        href: "talks/index.qmd"
      - text: "Video Lessons"
        href: "videolessons/index.qmd"
      - text: "AI Engineering Tutorials"
        href: "aiengineering/index.qmd"
      - text: "Datasets"
        href: "datasets/index.qmd"
      - text: "Now"
        href: now/index.qmd
      - text: "Tools"
        file: tools/index.qmd
      - text: "AI Disclosure Templates"
        file: aidisclosures/index.qmd
    
    right:
      - text: "{{< iconify bi rss size=1.1em title='RSS' >}}"
        href: atom.xml
      - text: "{{< iconify bi envelope size=1.1em title='E-mail' >}}"
        href: "mailto:sara@redteamai.org"
      - text: "{{< iconify bi github size=1.1em title='GitHub' >}}"
        href: https://github.com/sarakingsley
        rel: me
      - text: "{{< iconify bi linkedin size=1.1em title='LinkedIn' >}}"
        href: https://www.linkedin.com/in/sara-kingsley
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Sara C. Kingsley. Design derived from an Andrew Weiss Quarto website</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    center: |
      <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
     <!-- <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span> -->
    right: |
      <span class="faux-block">Made with {{< fa brands r-project >}} and [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/ath.scss
    grid: 
      body-width: 900px
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai